const efectos = [
"players cannot untap more than one land during their untap phases, que putada no?",
"creates a 0/30 token with the ability to defend, te salio bien no?",
"add infinite mana to your mana pool until end of turn, que joto wey",
"whenever you draw a card, draw three additional cards, maldito suertudo",
"spells you cast cost {0} to cast until end of turn, traiganle falda a la nena",
"at the benninging of your upkeep only the next turn take an extra turn after this one, aqui huele a joto",
"you may cast spells from your graveyard without paying their mana costs until end of turn, ya dije lo puto que eres?",
"at the beninging of your end step, if you cast three or more spells this turn, you win the game",
"Creatures you control get +X/+X where X is the number of cards in your hand.",
"You may play an additional five lands each turn.",
"Whenever a creature attacks you, destroy that creature.",
"At the beginning of your upkeep, create a 10/10 colorless Eldrazi creature token.",
"Whenever you gain life, draw that many cards.",
"Spells your opponents cast cost {5} more to cast.",
"Whenever a player casts a spell, counter it unless they pay half their life, rounded up.",
"If you would lose the game, instead shuffle your graveyard into your library and your life total becomes 20.",
"Artifacts you control have indestructible and hexproof.",
"Whenever a creature enters the battlefield under your control, fight target creature an opponent controls.",
"Your opponents cannot untap more than one permanent during their untap steps.",
"Whenever you deal combat damage to a player, exile the top ten cards of their library.",
"You may cast creature spells as though they had flash.",
"Whenever a creature dies, each opponent sacrifices a permanent.",
"At the beginning of combat on your turn, creatures you control gain double strike and trample.",
"You may activate abilities of creatures you control any number of times each turn.",
"Whenever you cast a black spell, each opponent loses 3 life and you gain 3 life.",
"All permanents you control phase out whenever an opponent casts a spell.",
"Whenever you exile a card, create a Treasure token.",
"You control your opponents during their turns.",
"At the beginning of your upkeep, search your library for any card and put it into your hand.",
"Creatures you control cannot be blocked.",
"Whenever an opponent sacrifices a permanent, create a token copy of it.",
"You may cast spells from exile.",
"Whenever a player draws a card except the first one they draw each turn, that player loses 2 life.",
"If damage would be dealt to you, prevent that damage and create that many Treasure tokens.",
"At the beginning of each end step, return all permanents from your graveyard to the battlefield.",
"Whenever you cast your second spell each turn, take an extra turn after this one.",
"Your creatures enter the battlefield with three additional +1/+1 counters.",
"Whenever a land enters the battlefield under your control, draw a card.",
"At the beginning of your upkeep, gain control of target permanent.",
"Whenever an opponent taps a land for mana, they lose 1 life.",
"You may cast cards from the top of your library.",
"Creatures your opponents control enter the battlefield tapped and do not untap during their controller's next untap step.",
"Whenever you attack, create a token copy of each attacking creature tapped and attacking.",
"If a spell or ability an opponent controls would target a permanent you control, counter that spell or ability.",
"creatures you control have annihilator 3 until end of turn",
"this spell cant be countered create a white avatar creature token with power and toughness each equal to the total life of all remaning players it has haste, indestructible, hexproof, lifelink, flying, menace, ward {10} and at the benninging of your next end step sacrifice it",
"Whenever you cast a spell, lose the game.",
"Creatures you control enter the battlefield tapped and do not untap.",
"At the beginning of your upkeep, sacrifice two lands.",
"You cannot gain life.",
"Whenever you draw a card, discard two cards.",
"Spells you cast cost life equal to their mana value.",
"Whenever a creature you control attacks, sacrifice it at end of combat.",
"Your maximum hand size is zero.",
"At the beginning of your end step, each opponent draws five cards.",
"Whenever you gain life, lose that much life instead.",
"Lands you control enter the battlefield tapped and deal 2 damage to you.",
"You skip your draw step.",
"Whenever you cast your second spell each turn, exile your hand.",
"Creatures you control have defender and cannot attack.",
"At the beginning of combat on your turn, tap all creatures you control.",
"Whenever a permanent enters the battlefield under your control, sacrifice another permanent.",
"Whenever you discard a card, lose 3 life.",
"Spells your opponents cast cost {0}.",
"You cannot activate abilities of artifacts or creatures.",
"Whenever you search your library, exile the searched card instead.",
"Whenever a creature dies, you lose 2 life.",
"At the beginning of your upkeep, an opponent gains control of target permanent you control.",
"You play with your hand revealed and your opponents may cast spells from it.",
"Whenever you tap a land for mana, discard a card.",
"Creatures you control get -3/-3.",
"At the beginning of your upkeep, mill twenty cards.",
"If you would draw a card, exile the top card of your library instead.",
"Whenever you attack, untap all creatures defending player controls.",
"Your opponents cannot lose the game.",
"At the beginning of your upkeep, your life total becomes 1.",
"Whenever you cast an instant or sorcery spell, counter it.",
"Artifacts you control lose all abilities.",
"Whenever you gain control of a permanent, sacrifice it.",
"Players may spend mana as though it were mana of any color except you.",
"Whenever you cast a creature spell, return a land you control to its owner's hand.",
"You cannot block.",
"Whenever you cast a spell during your turn, end the turn.",
"Your graveyard is exiled instead of existing.",
"Whenever a land enters the battlefield under your control, sacrifice that land.",
"At the beginning of your upkeep, exile the top half of your library rounded up.",
"Whenever you lose life, double that loss.",
"Creatures your opponents control have hexproof and indestructible.",
"At the end of each turn, discard your hand.",
"You cannot win the game.",
"Whenever you draw your second card each turn, lose 10 life.",
"Whenever you cast a spell, an opponent may copy it.",
"You skip your combat phase.",
"Whenever a creature enters the battlefield under an opponent's control, draw a card and lose 5 life.",
"At the beginning of your upkeep, sacrifice a permanent for each card in your hand.",
"When this permanent enters the battlefield, your life total becomes 1. Exile your hand, graveyard, and all permanents you control except this permanent.You can't gain life.Whenever you cast a spell, counter it.At the beginning of your upkeep, exile the top half of your library, rounded up Your opponents can't lose the game and you can't win the game",
];

const boton =
document. getElementById ("boton-azar");
const resultado =
document. getElementById ("resultado");

boton.addEventListener("click", () => {

const indice = Math. floor (Math.random() *
efectos.length);

resultado.textContent = efectos[indice];

});
